### ISSUE TITLE
LineSplitterTest test fail

### ISSUE THREAD

**Issue by delanym** [takari/concurrent-build-logger#4]
`mvn clean integration-test -Pmaven-distro`

```
[INFO] -------------------------------------------------------
[INFO]  T E S T S
[INFO] -------------------------------------------------------
[INFO] Running io.takari.maven.logging.internal.LineSplitterTest
[ERROR] Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.056 s <<< FAILURE! - in io.takari.maven.logging.internal.LineSplitterTest
[ERROR] initializationError(io.takari.maven.logging.internal.LineSplitterTest)  Time elapsed: 0.011 s  <<< ERROR!
java.lang.NoClassDefFoundError: org/hamcrest/SelfDescribing
Caused by: java.lang.ClassNotFoundException: org.hamcrest.SelfDescribing
```

**Comment by delanym** [comment]
Fixed with

    <dependency>
      <groupId>org.hamcrest</groupId>
      <artifactId>hamcrest-core</artifactId>
      <version>1.3</version>
    </dependency>

**Comment by delanym** [comment]
I still don't see any target/*/build.log with these 2 files in place

- /etc/maven/lib/ext/concurrent-build-logger-0.2.0-SNAPSHOT.jar
- /etc/maven/conf/logging/logback-byproduct.xml

`mvn clean install -T1.5C -Dskip.tests -Dmaven.logging=byproject`

Apache Maven 3.6.3
Maven home: /usr/share/maven
Java version: 1.8.0_275, vendor: Private Build, runtime: /usr/lib/jvm/java-8-openjdk-amd64/jre
Default locale: en_ZA, platform encoding: UTF-8
OS name: "linux", version: "5.4.0-58-generic", arch: "amd64", family: "unix"

**Comment by eliasbalasis** [comment]
I have done similar, using "dev" profile but no build.log files were generated.

e.g. clean deploy -B -Dmaven.logging=dev --builder smart -T 1C

**Comment by korwaat** [comment]
Hey Guys!
This project seems abandoned :(
But, I managed to get the logger to work.

Required readings:
- https://www.slf4j.org/manual.html#mdc
- https://www.slf4j.org/codes.html#StaticLoggerBinder
- https://maven.apache.org/maven-logging.html
- https://maven.apache.org/maven-logging.html#changing-the-slf4j-implementation
- https://www.slf4j.org/manual.html#swapping

What I did:
- I removed slf4j-simple JAR from the maven/lib directory (or renamed,nvm)
- I put the concurrent-build-logger builded jar into the maven/lib/ext directory along with the following: commons-logging-1.2.jar, jul-to-slf4j-1.7.24.jar, logback-classic-1.2.1.jar, logback-core-1.2.1.jar
- I put the logback-*.xml files into the maven/conf/logging directory

and that is all, the maven logger is worked.
(Important: -B or --batchmode is required when executing the maven plugin and goal!!!!)

I hope I can help to someone!

**Comment by eliasbalasis** [comment]
> Hey Guys! This project seems abandoned :( But, I managed to get the logger to work.
> 
> Required readings:
> 
> * https://www.slf4j.org/manual.html#mdc
> * https://www.slf4j.org/codes.html#StaticLoggerBinder
> * https://maven.apache.org/maven-logging.html
> * https://maven.apache.org/maven-logging.html#changing-the-slf4j-implementation
> * https://www.slf4j.org/manual.html#swapping
> 
> What I did:
> 
> * I removed slf4j-simple JAR from the maven/lib directory (or renamed,nvm)
> * I put the concurrent-build-logger builded jar into the maven/lib/ext directory along with the following: commons-logging-1.2.jar, jul-to-slf4j-1.7.24.jar, logback-classic-1.2.1.jar, logback-core-1.2.1.jar
> * I put the logback-*.xml files into the maven/conf/logging directory
> 
> and that is all, the maven logger is worked. (Important: -B or --batchmode is required when executing the maven plugin and goal!!!!)
> 
> I hope I can help to someone!

This is indeed helpful.
I managed to achieve the same.

I guess the -B option is only required for headless environments and doesn't control the loading of the extension.

Are you using the "byproject" logger? If yes, is it working?
I can't get mine to work for forked ITs on parallel builds.

**Comment by cstamas** [comment]
Merged https://github.com/takari/concurrent-build-logger/pull/7 FYI
